# Quantumult X rewrite-only - 哈士奇签到
[rewrite_local]
^https?:\/\/vip\.ioshashiqi\.com\/aspx3\/mobile\/.*$ url script-request-header https://raw.githubusercontent.com/eleven252412/ioshashiqi-quanx-checkin/main/ioshashiqi-checkin-quanx.js
